services:
  backend:
    build: .  
    ports:
      - "5000:5000"  

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      